physical_exam_terms = [
    # Xanthomas
    "Achilles Tendinous Xanthomas",
    "Achilles tendon xanthoma",
    "Cutaneous Xanthomas",
    "Nodular Achilles Tendons",
    "Palmar Xanthomas",
    "Palpable Xanthomas",
    "Possible Tendon Xanthom",
    "Tendinous Xanthoma",
    "Tendinous Xanthomas",
    "Tendinous Xanthomata",
    "Tendon Xanthoma",
    "Tendon Xanthomas",
    "Tendon Xanthomata",
    "Thickened Achilles Tendon",
    "Thickening Of Achilles Tendon",
    "Tuberoeruptive Xanthomas",
    "Tuberous Xanthomas",
    "Xanthomas",
    "Xanthomas Of Achilles Tendon",
    "Xanthomas Of The Hands",
    "Xanthomas On The Extensor Surfaces",
    
    # corneal arcus
    "Corneal arcus",
    "Arcus cornealis",
    "Early arcus senilis",
]

physical_exam_exclude_terms = [
    "Eruptive xanthomas",
    "Irruptive xanthomas",
    "Xanthomas around both eyes",
    "Xanthomas around the left eye",
    "Xanthomas around the right eye",
    "Eyelid xanthomas",
    "Eye lid xanthomas",
    "Xanthomas on the eye",
    "Xanthomas over eyelids",
    "Xanthomas over the eyes",
    "Xanthomas over both eyelids",
    "Xanthomas on the upper lids",
    "Xanthomas beneath both eyes",
    "Xanthomas beneath eye(s)",
    "Xanthomas beneath eyelid",
    "Xanthomas on the face",
]
